name: Automatic Testing

on:
    push:
      branches: ["main"]
      paths:
      # only run if src
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - "src/**"
      - "pom.xml"
    pull_request:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
                type: choice
                options:
                - info
                - warning
                - debug

jobs:
  test:
    runs-on: [self-hosted, Ubuntu]
    permissions:
        contents: read
        packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'

      - name: Install Maven
        run: apt-get update; apt-get install maven -y

      - name: Build with Maven
        run: mvn clean validate compile test test-compile --file pom.xml